'use strict';
// 07.10: независимый проход. Только tg/mock; любые остальные сети закрыты.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),M=require('./mock'),S=require('./ds5-scenes');
const OUT=path.resolve(__dirname,'../docs/reviews/2026-10-07-prohod');fs.mkdirSync(OUT,{recursive:true});
const goal={text:'75 кг к концу января',wt:'down',rate:-.6,from:M.Д(33),w0:92.3,by:'2027-02-10'};
const progress={anchor:M.Д(19),anchorW:88.3,rate:-.6,gap:.7,fact:-4.7,plan:-5.4,onTrack:false,verdict:{state:'стоит',text:'Неделя без снижения. Одна такая бывает от соли, воды и гликогена; вторая подряд — плато.'},eta:{pace:-.43,weeks:29,date:'2027-04-26'},sila:{verdict:'растёт',up:2,flat:1,down:1,rows:[{name:'Подтягивания',now:{w:0,r:8,date:M.Д(1)},was:{w:0,r:6,date:M.Д(12)},pct:33}]}};
const meal={id:'d1',kind:'ужин',text:'Куриная грудка с гречкой',мин:30,kcal:520,prot:62,items:[{name:'Куриная грудка',g:220,kcal:360,prot:60}]};
const menu={ok:true,span:'day',from:M.Д(-1),at:Date.now(),note:'Подставное меню.',дни:[{date:M.Д(-1),зал:true,спорт:[],норма:{kcal:1850,prot:160},kcal:1750,prot:159,приёмы:[{...meal,id:'b',kind:'завтрак'},{...meal,id:'l',kind:'обед'},meal]}],покупки:{семья:2,дней:1,дома:['Рис'],отделы:[{отдел:'Мясо',список:[{имя:'Куриная грудка',сколько:'600 г',g:600}]}]}};
const base={me:{sex:'m',age:34,ht:178,bw:88.1,wt:'down',gym:'muscle',only:'all',level:'mid',place:'gym',lim:[],eq:[]},time:'19:40',hist:M.журнал(),meas:M.замеры(),goal,progress,menu:{day:menu,week:{...menu,span:'week'},завтра:M.Д(-1)},onMenu:r=>{const span=JSON.parse(r.request().postData()).span;return {...menu,span,from:span==='today'?M.TODAY:M.Д(-1),дни:span==='week'?Array.from({length:7},(_,i)=>({...menu.дни[0],date:M.Д(-i-1)})):menu.дни}},onRecipe:()=>({ok:true,шаги:['Сварить гречку.','Запечь курицу.']})};
const scenes=[{name:'log-empty',o:{page:'log',meas:null,hist:[]}}, {name:'profile-full',o:{page:'home'},act:async p=>{await p.click('#profbtn')}},...['home','gym','log','ref','food','eat','circle'].map(page=>({name:page,o:{page}})),...S.scenes.map(name=>({name,ds:true})),
 {name:'arc-expanded',o:{page:'home'},act:async p=>{await p.locator('[data-hx]').first().click()}},
 ...['fat','prot'].map(v=>({name:'body-'+v,o:{page:'home'},act:async p=>{await p.locator('[data-vzv="'+v+'"]').click();await p.locator('.vz').scrollIntoViewIfNeeded()}})),
 {name:'gym-active',o:{page:'gym'},act:async p=>{await p.locator('#list .exrow').first().click();await p.locator('.setrow .ok').first().click()}},
 {name:'food-yesterday',o:{page:'food'},act:async p=>{await p.locator('[data-fnav="-1"]').click()}},
 ...['day','week','buy'].map(s=>({name:'menu-'+s,o:{page:'eat'},act:async p=>{await p.locator('[data-eseg="'+s+'"]').click()}})),
 {name:'catalog-search',o:{page:'ref'},act:async p=>{await p.fill('#pcatsearch','жим')}},
 {name:'profile-household',o:{page:'home'},act:async p=>{await p.click('#profbtn');await p.click('#bttoggle')}},
 {name:'profile-health',o:{page:'home'},act:async p=>{await p.click('#profbtn');await p.click('#zdtoggle')}},
];
const selected=process.argv[2]?new Set(process.argv[2].split(',')):null;
const result=selected&&fs.existsSync(path.join(OUT,'inventory.json'))?JSON.parse(fs.readFileSync(path.join(OUT,'inventory.json'))).filter(r=>!selected.has(r.name)):[];
async function offline(p){await p.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1')return r.abort();let f=u.pathname==='/'?'index.html':u.pathname.slice(1);if(f.startsWith('p/'))f='tg/fixtures/'+f.slice(2);const file=path.resolve(__dirname,'..',f);try{await r.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.json':'application/json','.woff2':'font/woff2','.jpg':'image/jpeg','.png':'image/png'})[path.extname(file)]||'application/octet-stream'})}catch{await r.fulfill({status:404,body:''})}})}
const state=()=>{const visible=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none'};const modal=[...document.querySelectorAll('.modal.show')].at(-1),root=modal||document.querySelector('.page:not(.hide)');return {page:root?.id,text:root?.innerText,controls:[...(root||document).querySelectorAll('button,summary,input,select,textarea,[role="button"],[data-mid],.exrow')].filter(visible).map(e=>{const r=e.getBoundingClientRect();return {tag:e.tagName,id:e.id,cls:e.className,text:(e.innerText||e.getAttribute('aria-label')||e.placeholder||'').trim(),disabled:e.disabled||false,rect:[r.x,r.y,r.width,r.height],data:{...e.dataset}}}),overflow:[...document.querySelectorAll('body *')].filter(e=>!e.ownerSVGElement&&visible(e)).filter(e=>{let r=e.getBoundingClientRect();return r.right>innerWidth+2||r.left< -2}).map(e=>({id:e.id,cls:e.className,text:e.innerText?.slice(0,60)})).slice(0,20)}};
(async()=>{const b=await chromium.launch();try{for(const theme of ['light','dark'])for(const width of [390,320])for(const s of scenes){if(selected&&!selected.has(s.name))continue;const p=await b.newPage({viewport:{width,height:844},deviceScaleFactor:1});p.setDefaultTimeout(4500);await offline(p);const row={name:s.name,theme,width,errors:[],network:[]};p.on('pageerror',e=>row.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)row.network.push([r.status(),r.url()])});try{if(s.ds)await S.open(p,s.name,theme);else{await M.поднять(p,{...base,...s.o,theme});if(s.act)await s.act(p)}await p.waitForTimeout(250);row.state=await p.evaluate(state);await p.screenshot({path:path.join(OUT,`${s.name}-${theme}-${width}.png`),fullPage:!s.ds&&!(await p.locator('.modal.show').count())});console.log('OK',s.name,theme,width)}catch(e){row.failure=e.message;console.log('FAIL',s.name,theme,width,e.message.split('\n')[0])}result.push(row);fs.writeFileSync(path.join(OUT,'inventory.json'),JSON.stringify(result,null,2));await p.close()}}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
