'use strict';
const {chromium}=require('playwright'),M=require('./mock'),fs=require('fs'),path=require('path');
const out=path.resolve(__dirname,'../docs/reviews/2026-10-07-prohod');fs.mkdirSync(out,{recursive:true});
const selected=process.argv[2]?new Set(process.argv[2].split(',')):null;const rows=selected&&fs.existsSync(path.join(out,'proofs.json'))?JSON.parse(fs.readFileSync(path.join(out,'proofs.json'))).filter(r=>!selected.has(r.name)):[];
async function offline(p){await p.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1')return r.abort();let f=u.pathname==='/'?'index.html':u.pathname.slice(1);if(f.startsWith('p/'))f='tg/fixtures/'+f.slice(2);try{await r.fulfill({body:fs.readFileSync(path.resolve(__dirname,'..',f)),contentType:({'.html':'text/html','.json':'application/json','.woff2':'font/woff2','.jpg':'image/jpeg','.png':'image/png'})[path.extname(f)]||'application/octet-stream'})}catch{await r.fulfill({status:404,body:''})}})}
(async()=>{const b=await chromium.launch();try{for(const theme of ['dark','light'])for(const width of [320,390]){
 async function run(name,opts,act){if(selected&&!selected.has(name))return;const p=await b.newPage({viewport:{width,height:844}});p.setDefaultTimeout(5000);await offline(p);let requests=[];const opt={theme,page:'food',...opts};const route=opt.handleRoute;opt.handleRoute=async r=>{requests.push({url:new URL(r.request().url()).pathname,body:r.request().postData()});return route?route(r):false};const row={name,theme,width};try{await M.поднять(p,opt);row.result=await act(p,requests);await p.screenshot({path:path.join(out,`proof-${name}-${theme}-${width}.png`)});console.log(name,theme,width,JSON.stringify(row.result))}catch(e){row.error=e.message;console.log('ERROR',name,e.message)}rows.push(row);await p.close();fs.writeFileSync(path.join(out,'proofs.json'),JSON.stringify(rows,null,2))}
 await run('backdate',{},async(p,rs)=>{await p.click('[data-fnav="-1"]');await p.waitForTimeout(200);const day=await p.locator('#fnav').innerText();await p.click('#food-add');await p.fill('#ctext','Съел яблоко');await p.click('#csend');await p.waitForTimeout(300);return {selected:day,expected:M.Д(1),sent:rs.filter(x=>x.url==='/coach').map(x=>JSON.parse(x.body))}});
 await run('chat-failure',{handleRoute:async r=>{if(new URL(r.request().url()).pathname!=='/coach')return false;await r.fulfill({status:503,contentType:'application/json',body:'{"error":"Сервис временно недоступен"}'});return true}},async p=>{await p.click('#coachnav');await p.fill('#ctext','Непотерянный черновик ужина');await p.setInputFiles('#cfile',path.join(__dirname,'fixtures/a.jpg'));await p.waitForTimeout(250);await p.click('#csend');await p.waitForTimeout(350);return {input:await p.locator('#ctext').inputValue(),text:await p.locator('#coachm').innerText(),attachment:await p.locator('#cattach').innerText()}});
 await run('day-race',{handleRoute:async r=>{let u=new URL(r.request().url());if(u.pathname!=='/day')return false;const date=u.searchParams.get('date')||M.TODAY;if(date===M.Д(1))await new Promise(r=>setTimeout(r,900));await r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,day:M.день({date,meals:[{id:date,t:'12:00',kind:'обед',text:'ЗАПИСЬ '+date,kcal:500,prot:30}]})})});return true}},async p=>{await p.click('[data-fnav="-1"]');await p.click('[data-fnav="-1"]');await p.waitForTimeout(1300);return {expected:M.Д(2),header:await p.locator('#fnav').innerText(),meals:await p.locator('#fmeals').innerText()}});

 await run('buy-error',{page:'eat',menu:{day:{span:'day',from:M.Д(-1),дни:[],покупки:{отделы:[],дома:[]}}},handleRoute:async r=>{if(new URL(r.request().url()).pathname!=='/menu/send')return false;await r.fulfill({status:503,contentType:'application/json',body:'{"error":"Не удалось отправить покупки"}'});return true}},async p=>{await p.click('[data-eseg="buy"]');await p.click('[data-msend="day:buy"]');await p.waitForTimeout(300);return {text:await p.locator('#eatbody').innerText()}});
 await run('day-error',{handleRoute:async r=>{const u=new URL(r.request().url());if(u.pathname!=='/day'||u.searchParams.get('date')!==M.Д(1))return false;await r.fulfill({status:503,contentType:'application/json',body:'{"error":"Ошибка загрузки дня"}'});return true}},async p=>{await p.click('[data-fnav="-1"]');await p.waitForTimeout(800);return {header:await p.locator('#fnav').innerText(),text:await p.locator('#p-food').innerText()}});

 for(const entry of ['profile','coach'])await run('subscription-'+entry,{page:'home',sub:'нет'},async p=>{if(entry==='profile'){await p.click('#profbtn');await p.click('#sub-on')}else{await p.click('#coachnav');await p.fill('#ctext','Что съесть?');await p.click('#csend')}await p.waitForTimeout(400);return await p.evaluate(()=>{const b=document.getElementById('sub-buy'),r=b.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);const input=document.getElementById('sub-code'),ir=input.getBoundingClientRect(),is=getComputedStyle(input);return {promo:{rect:[ir.x,ir.y,ir.width,ir.height],background:is.backgroundColor,font:is.fontSize},subShow:document.getElementById('subm').classList.contains('show'),rect:[r.x,r.y,r.width,r.height],topModal:hit?.closest('.modal')?.id,hit:hit?.outerHTML.slice(0,180),layers:[...document.querySelectorAll('.modal.show')].map(e=>({id:e.id,z:getComputedStyle(e).zIndex}))}})});
 await run('measure-invalid',{page:'home'},async(p,rs)=>{await p.fill('#fw','abc');await p.click('#fmsave');await p.waitForTimeout(200);return {sent:rs.filter(x=>x.url==='/measure'),message:await p.locator('#fmreply').innerText(),value:await p.locator('#fw').inputValue()}});
 await run('measure-failure',{page:'home',handleRoute:async r=>{if(new URL(r.request().url()).pathname!=='/measure')return false;await r.fulfill({status:503,contentType:'application/json',body:'{"error":"Не удалось сохранить замер"}'});return true}},async p=>{await p.fill('#fw','87.2');await p.click('#fmsave');await p.waitForTimeout(300);const texts=await p.evaluate(()=>Array.from(document.querySelectorAll('body *')).filter(e=>e.children.length===0&&/Не удалось сохранить замер/.test(e.textContent)).map(e=>({id:e.id,text:e.textContent,visible:!!e.getBoundingClientRect().height,parent:e.closest('.page')?.id})));return {texts,input:await p.locator('#fw').inputValue()}});
 }}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
