'use strict';
const {chromium}=require('playwright'),M=require('./mock'),fs=require('fs'),path=require('path');
const out=process.argv[2];if(require.main===module)fs.mkdirSync(out,{recursive:true});
const meals=['09:53','10:26','10:28','14:03','14:48'].map((t,i)=>({id:i+1,t,kind:['завтрак','обед','перекус','перекус','перекус'][i],img:'/p/'+(i%2?'b':'a')+'.jpg',kcal:448,prot:38,text:'Приём пищи'}));
const day={date:M.Д(-1),норма:{kcal:2110,prot:165},kcal:2050,prot:162,приёмы:[{id:'b1',kind:'завтрак',text:'Омлет с творогом',мин:10,kcal:430,prot:42,items:[{name:'яйца',g:165},{name:'творог',g:150}]},{id:'b2',kind:'обед',text:'Курица с рисом и овощами',мин:25,kcal:620,prot:52,items:[{name:'курица',g:180},{name:'рис',g:150},{name:'овощи',g:200}]},{id:'b3',kind:'перекус',text:'Творог с ягодами',мин:3,kcal:280,prot:34,items:[{name:'творог',g:200},{name:'ягоды',g:80}]},{id:'b4',kind:'ужин',text:'Рыба с картофелем',мин:25,kcal:720,prot:34,items:[{name:'рыба',g:180},{name:'картофель',g:250}]}]};
const menu={ok:true,span:'day',from:M.Д(-1),at:Date.now(),note:'Меню учитывает норму дня и привычные блюда.',дни:[day]};
function opts(theme){return {theme,me:{age:34,ht:178,sex:'m',bw:88.7,goal:'fat',wt:'down',gym:'muscle',level:'mid',place:'gym',med:{at:Date.now(),none:1}},time:'16:00',hist:M.журнал(),meas:M.замеры(),week:{days:M.неделя().days.map(d=>d.date===M.TODAY?{...d,kcal:2240,prot:191,n:5,tg:{kcal:1650,prot:160}}:d)},score:{r:5.6,why:[{t:'калории: перебор',совет:'дальше порция поменьше'}]},day:{meals,kcal:2240,prot:191,targets:{...M.день().targets,kcal:1650,prot:160}},goal:{text:'75 кг к концу января · мышцы и силу сохраняем',wt:'down',rate:-.6,from:M.Д(29),w0:92},progress:{anchor:M.Д(14),anchorW:89,rate:-.6,gap:1,onTrack:false,w0:92.3,now:87.5,fact:-4.8,plan:-5.8,by:'2027-02-10',verdict:{state:'стоит',text:'Неделя без снижения: −0,0 кг по средним (3 замера). Одна такая бывает от соли, воды и гликогена; вторая подряд — плато.'},eta:{date:'2027-04-25'},sila:{verdict:'падает',up:7,flat:11,down:10,rows:[{name:'Подтягивания',was:{w:0,r:6,date:M.Д(15)},now:{w:0,r:8,date:M.Д(1)},pct:33}]}},menu:{day:menu,завтра:M.Д(-1)},onMenu:()=>menu};}
module.exports={opts};
if(require.main===module)(async()=>{const b=await chromium.launch();try{for(const theme of ['dark','light'])for(const width of [390,320]){const p=await b.newPage({viewport:{width,height:844},deviceScaleFactor:2});await M.поднять(p,opts(theme));await p.screenshot({path:path.join(out,`home-${theme}-${width}.png`)});await p.locator('.day-events summary').click();await p.screenshot({path:path.join(out,`events-${theme}-${width}.png`)});await p.locator('.day-events summary').click();await p.locator('.vz').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,`body-${theme}-${width}.png`)});await p.click('#profbtn');await p.screenshot({path:path.join(out,`profile-${theme}-${width}.png`)});await p.click('#profclose');await p.click('.l1 [data-page="food"]');await p.waitForTimeout(300);await p.screenshot({path:path.join(out,`food-${theme}-${width}.png`)});await p.locator('#fweek').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,`week-${theme}-${width}.png`)});await p.locator('[data-zseg="eat"]:visible').click();await p.click('[data-eseg="day"]');await p.waitForTimeout(300);await p.screenshot({path:path.join(out,`menu-${theme}-${width}.png`)});await p.close();}}finally{await b.close()}})();
